### ISSUE TITLE
PDOStatement::execute(): SQLSTATE[HY093]: Invalid parameter number

### ISSUE THREAD

**Issue by Nostromio** [Eole-dev/authphpbb3#11]
Hello, i've updated your plugin from version date 2017-01-26 to 2019-01-17.

When i open user manager, i see the following error:

Warning: PDOStatement::execute(): SQLSTATE[HY093]: Invalid parameter number: number of bound variables does not match number of tokens in /www/htdocs/xxx/wb/wiki/lib/plugins/authphpbb3/auth.php on line 359

I'm using dokuwiki release 2018-04-22a "Greebo"

What can i do? Thanks for your help

**Comment by Nostromio** [comment]
I've found another issue: in "authphpbb3/lang/de/lang.php" there is a missing ";" on line 12, which breaks all my javascript navigation.

Nevertheless, in user manager, the error message from above is still existend!

**Comment by Eole-dev** [comment]
Hello,

I updated the plugin to fix both issues (hopefully).

**Comment by Nostromio** [comment]
Thank you for your fix! I'm afraid, but this didn't solve the problem for me. Now i get the following error:
Warning: PDOStatement::execute(): SQLSTATE[HY093]: Invalid parameter number: number of bound variables does not match number of tokens in /www/htdocs/xxx/wb/xxx/lib/plugins/authphpbb3/auth.php on line **367**

**Comment by Eole-dev** [comment]
I don't have my development environment so I'm using you, I'm sorry :)

I tried to fix this issue again (file auth.php has been updated). Could you please test in your environment?

**Comment by Nostromio** [comment]
So, excuse my delay ... family, kids, etc.
Now, it works a little bit ... but: ;-)
- The Result Table has 20 rows
- Username is always a number starting from 0 to 19 (should'nt it be the username?)
- User full name is the username (i think username_clean would be correct?), E-Mail and Groups are okay
- Exporting all users is working and correct
- Search in "Full Name" isn't working

The solution is near! Thanks for your work!

**Comment by Eole-dev** [comment]
With my last changes, the issue should be fixed.
In the search form, you need to specify both User and Real name if you want to filter by name.

**Comment by Nostromio** [comment]
Yeah, issue fixed!
If i have to search for both, then it is working!
Great! Thx!

**Comment by Eole-dev** [comment]
Thank you for your reports and your time.
